### PR TITLE
Remove outdated warning about version 1.0.0

### PR DESCRIPTION
**Pull request by leaf-fastly**
Version 1.0.4 works with current stemcells.

### CODE REVIEW

**Comment by jncd** [comment]
Hi @leaf-sigsci 
I just saw that you removed the warning that v1.0.0 doesn't work with Xenial stemcells.
Why is that? I appreciate that v1.0.4 works with Xenial, but shouldn't users who haven't upgraded to v1.0.4 be warned that they can't use Xenial stemcells?

**Comment by leaf-fastly** [comment]
Hi Jane, that makes complete sense; i was asked to remove the warning because it seemed to leave the impression with readers that the tile, overall, was not supported on newer stemcells.
I pointed out that 1.0.4 != 1.0.0, but it didn't seem obvious enough.
I'll try to write up something of a compromise and re-submit the PR.

**Comment by leaf-fastly** [comment]
@jncd: is the current state of this change better?

**Comment by tehall16** [comment]
No 1.0.0 version is live anymore, so closing this out

**Pull request closed without merging**
